export enum BinaryType {
  Api = 'api',
  Bucket = 'bucket',
  Cypress = 'cypress',
  Electron = 'electron',
  Firefox = 'firefox',
  GitHub = 'github',
  Imagemin = 'imagemin',
  Node = 'node',
  NodePreGyp = 'nodePreGyp',
  Nwjs = 'nwjs',
  Playwright = 'playwright',
  Puppeteer = 'puppeteer',
  Prisma = 'prisma',
  Sqlcipher = 'sqlcipher',
  ChromeForTesting = 'chromeForTesting',
  Edgedriver = 'edgedriver',
}
