ALTER TABLE users ADD COLUMN IF NOT EXISTS fullname varchar(200) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS homepage varchar(400) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS twitter varchar(100) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github varchar(100) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS freenode varchar(100) DEFAULT NULL;
