# https://github.com/marketplace/actions/sql-review

on: [pull_request]

jobs:
  sql-review:
    runs-on: ubuntu-latest
    name: SQL Review
    steps:
      - uses: actions/checkout@v3
      - name: Check SQL
        uses: bytebase/sql-review-action@main
        with:
          database-type: "MYSQL"
          file-pattern: ^sql/.*\.sql$
